# This is a basic workflow to help you get started with Actions
# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build main
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            LaTeX_tips.tex
            ex_plot.tex
          args: "-pdf -file-line-error -interaction=nonstopmode"

      # Upload
      #- name: Upload LaTeX_tips
        #uses: actions/upload-artifact@v2
        #with:
          #name: LaTeX_tips.pdf
          #path: LaTeX_tips.pdf
      #- name: Upload ex_plot
        #uses: actions/upload-artifact@v2
        #with:
          #name: ex_plot.pdf
          #path: ex_plot.pdf
      # Release
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "LaTeX_tips.pdf,ex_plot.pdf"
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
